version: '3.7'

services:
  webapp:
    build: .
    container_name: web_service
    image: webapp
    ports:
      - "80"

    depends_on:
      - database
    environment:
      POSTGRES_USER: hadeel
      POSTGRES_PASSWORD: hadeel123
      POSTGRES_DB: test_db
      POSTGRES_HOST: database
      POSTGRES_PORT: "5432"
      VIRTUAL_HOST: web_service.docker
    

  database:
    container_name: database_service
    image: postgres:14.2
    environment:
      POSTGRES_USER: hadeel
      POSTGRES_PASSWORD: hadeel123
      POSTGRES_DB: test_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432"

  pgadmin:
    container_name: pg_service
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com 
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: "8080"
    ports:
      - "5040:8080"
 
 
 
 
 