version: '3.7'

services:
  webapp:
    build: .
    container_name: web_service
    image: webapp
    depends_on:
      - database
    environment:
      POSTGRES_USER: hadeel
      POSTGRES_PASSWORD: hadeel123
      POSTGRES_DB: test_db
      POSTGRES_HOST: database
      POSTGRES_PORT: "5432"
      VIRTUAL_HOST: web_service.docker
  
  webapp_base:
    extends: db_base
    build: .
    container_name: web_service1
    image: webapp
    volumes:
      - ${PWD}:/main
    command: ["echo", "build successful"]

  db_base:
    container_name: db
    image: postgres:14.2
    volumes:
      - ${PWD}:/main
    command: ["echo", "build db successful"]

  webapp_test:
    extends: webapp_base
    container_name: webapp_test
    command: sh -c "pytest --cov=FLASKAPP tests/"

  database:
    container_name: database_service
    image: postgres:14.2
    environment:
      POSTGRES_USER: hadeel
      POSTGRES_PASSWORD: hadeel123
      POSTGRES_DB: test_db
      POSTGRES_HOST_AUTH_METHOD: trust
      VIRTUAL_HOST: database.docker
    ports:
      - "5432"


 
 
 
 